apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: alicloud-disk-essd-multi-attach-wait
  resources:
    requests:
      storage: 20Gi